---
- name: 웹서버 설치
  hosts: all
  become: yes
  
  tasks:
    - name: nginx 설치하기
      shell: docker service create \
      --name nginx_install --contstraint node.role==worker \
      -p 8080:80 --with-registry-auth nginx 
     